### PR TITLE
Added comments and logging... somehow, the England object is being ch…

### PR DESCRIPTION
**Pull request by PropeReferio**
#1 

Somehow, whichever country is chosen as the intialized state variable `countryData` is the one that can't update again... but actually, some of that country data comes through, like total cases, and the country's name in the `TitleText`.
I added some logging. When you look at the Country objects in the browser, you'll see that the `line1` property is actually changing!

I really don't get it. The array that's passed to `CountrySelectChart()` is being changed, and I see nothing in the code that would be doing it!

If this helps you, would you merge my pull request and tag it with `hacktoberfest-accepted`?

### CODE REVIEW

**Review by oldben87 — APPROVED** [review]
Hacktoberfest - approved

**Review by oldben87 — APPROVED** [review]

**Comment by PropeReferio** [comment]
Hey oldben, could you tag/mark this `hacktoberfest-accepted`?

**Comment by oldben87** [comment]
did you mean the commit or this issue?
I think i have already tagged your commit with hacktober-accepted:
Screenshot_20201029-151711_Chrome
Not too familar with tagging and labels

**Comment by PropeReferio** [comment]
Oh, I see it! Thanks!

**Pull request merged**
